export const FILTRAR_CARRITO_A_MOSTRAR = "FILTRAR_CARRITO_A_MOSTRAR";
export const FILTRAR_FAVORITOS_A_MOSTRAR = "FILTRAR_FAVORITOS_A_MOSTRAR"
export const RESET_CARRITO_Y_FAVORITOS = "RESET_CARRITO_Y_FAVORITOS"