export const OBTENER_USER_INFO = "OBTENER_USER_INFO";
export const OBTENER_USER_CARRITO = "OBTENER_USER_CARRITO";
export const OBTENER_USER_FAVORITOS = "OBTENER_USER_FAVORITOS";
export const USUARIO_EN_LINEA = "USUARIO_EN_LINEA";
export const USUARIO_ROL = "USUARIO_ROL";
export const RESET_USUARIO = "RESET_USUARIO"
export const OBTENER_USUARIO_HISTORIAL_COMPRAS = "OBTENER_USUARIO_HISTORIAL_COMPRAS"